'use strict';
// Task 6: do repeated mechanical work with plain JS (zero model tokens).
// A task opts in by carrying an `automation` block, e.g.
//   "automation": { "script": "scaffold", "files": [ { "path": "docs/x.md", "template": "md", "title": "X" } ] }
// Supported templates: md, json, js, ts, text (or inline "content").
const fs = require('fs');
const path = require('path');
const { loadFolders, folderTasks, findTask, writeJson } = require('../lib/common');
const { completeTask } = require('./complete');

const TEMPLATES = {
  md: (f) => `# ${f.title || path.basename(f.path, '.md')}\n\n${f.description || 'TODO'}\n`,
  json: (f) => JSON.stringify(f.data || {}, null, 2) + '\n',
  js: (f) => `'use strict';\n// ${f.description || path.basename(f.path)}\n\nmodule.exports = {};\n`,
  ts: (f) => `// ${f.description || path.basename(f.path)}\nexport {};\n`,
  text: (f) => `${f.description || ''}\n`,
};

function scaffoldTask(task, targetRoot, { dryRun } = {}) {
  const spec = task.automation;
  if (!spec || spec.script !== 'scaffold' || !Array.isArray(spec.files)) throw new Error(`${task.id}: no automation.scaffold spec`);
  const created = [];
  for (const f of spec.files) {
    const abs = path.resolve(targetRoot, f.path);
    if (!abs.startsWith(path.resolve(targetRoot) + path.sep)) throw new Error(`${task.id}: path escapes target root: ${f.path}`);
    if (fs.existsSync(abs)) continue;
    const body = f.content ?? (TEMPLATES[f.template || 'text'] || TEMPLATES.text)(f);
    if (!dryRun) {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, body, 'utf8');
    }
    created.push(f.path);
  }
  return created;
}

function runScripted(args) {
  const folders = loadFolders();
  const target = path.resolve(args.dir || process.cwd());
  const items = args._[0] ? [findTask(folders, args._[0])].filter(Boolean) : [...folders.values()].flatMap((f) => folderTasks(f));
  let done = 0;
  for (const { task, file } of items) {
    if (task.status !== 'PENDING' || !task.automation) continue;
    if (!args._[0] && !task.executionPlan?.scriptable) continue;
    try {
      const created = scaffoldTask(task, target, { dryRun: !!args['dry-run'] });
      console.log(`${task.id}: ${created.length} file(s)${args['dry-run'] ? ' (dry run)' : ''}`);
      if (!args['dry-run']) {
        task.artifacts = created;
        writeJson(file.file, file.data);
        completeTask(loadFolders(), task.id, { model: 'js-script', confidence: 1, notes: `Generated by tools scaffold (${created.length} files)`, force: true });
      }
      done++;
    } catch (e) {
      console.error(e.message);
    }
  }
  console.log(`scripted tasks processed: ${done}`);
}

module.exports = { scaffoldTask, runScripted };

if (require.main === module) {
  const { parseArgs } = require('../lib/common');
  runScripted(parseArgs(process.argv.slice(2)));
}
